name: Hello World Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Afficher Hello World
        run: echo "Hello World ✅"